# VULNERABILIDADE: Secret com dados em base64 obvio (facilmente decodificavel)
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: vulnerable-namespace
type: Opaque
data:
  # Secrets em manifesto versionado no Git
  username: YWRtaW4=  # admin
  password: cGFzc3dvcmQxMjM=  # password123
  api-key: c2stcHJvai0xMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=  # sk-proj-1234567890abcdefghijklmnopqrstuvwxyz
  aws-access-key: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=  # AKIAIOSFODNN7EXAMPLE
  aws-secret-key: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==  # wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
